### PR TITLE
Finish week 0 and week 1 walkthrough

### PR DESCRIPTION
**Pull request by cccntu**
Customized README.md

### CODE REVIEW

**Comment by cccntu** [comment]
@phadke-sps-tw Can you review this? Thanks!

**Comment by phadke-sps-tw** [comment]
Sure. please add me for doing a review of the PR.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review

**Comment by cccntu** [comment]
@phadke-sps-tw  Thanks, I did not know that. Is it working now?
By the way, I am working on week2, and the walkthrough recommends me to submit a pull request every step, should I do that or should I put all commits in week2 in the same branch like this?

**Comment by phadke-sps-tw** [comment]
Yes it's working now. It's better to create a new PR for a major step, and put all minor changes in it.

**Pull request merged**
